/** Declaration file generated by dts-gen */
declare module 'subcommander'{

  export class Command {
    constructor(name: any, props: any);

    command(name: any, props: any): any;

    end(): any;

    noColors(): any;

    option(name: any, props: any): any;

    parse(argv: any): any;

    reset(): any;

    scriptName(name: any): any;

    usage(): any;

  }


export class Option {
  constructor(name: any, props: any);

  getUsage(): any;

}

export const args: any[];

export const callback: any;

export const commands: {
};

export const desc: string;

export const name: any;

export const options: {
};

export const parent: any;

export const parsed: {
};

export const script: string;

export function command(name: any, props: any): any;

export function end(): any;

export function noColors(): any;

export function option(name: any, props: any): any;

export function parse(argv: any): any;

export function reset(): any;

export function scriptName(name: any): any;

export function usage(): any;


}



